"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-*xp6q6rypvr83&am#!h++rnl-l_h2e1qc%q=3m&4+^^j4h5pzm')

DEBUG = os.getenv('DEBUG', 'True') == 'True'
LOCAL_DEVELOPMENT = (
    not os.getenv('DATABASE_URL')
    and os.getenv('DB_HOST', 'localhost') in ('localhost', '127.0.0.1')
)

ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')
    if host.strip()
]

if DEBUG or LOCAL_DEVELOPMENT:
    # '10.0.2.2' is the Android emulator's fixed alias for the host
    # machine's localhost (see mobile/src/api/config.js) — without it, every
    # request from the emulator gets rejected with DisallowedHost before it
    # even reaches a view.
    for host in ['localhost', '127.0.0.1', '[::1]', '10.0.2.2']:
        if host not in ALLOWED_HOSTS:
            ALLOWED_HOSTS.append(host)
    # A physical phone on the same Wi-Fi hits the backend via the dev
    # machine's LAN IP (see mobile/.env), which changes with DHCP — so in
    # local dev accept any host rather than chasing the current IP.
    if '*' not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append('*')

# Render.com sets this automatically
RENDER_EXTERNAL_HOSTNAME = os.getenv('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME and RENDER_EXTERNAL_HOSTNAME not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'clubs',
    'events',
    'participation',
    'payments',
    'rest_framework',
    'corsheaders',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',  # Protects all APIs by default
    ]
}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# CORS_ALLOWED_ORIGINS = os.getenv(
#     'CORS_ALLOWED_ORIGINS',
#     'http://localhost:3000,http://localhost:5173,http://127.0.0.1:5173,https://events-and-clubs-management-54772uwg7.vercel.app'
# ).split(',')
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

if os.getenv('DATABASE_URL'):
    DATABASES = {
        'default': dj_database_url.config(
            default=os.getenv('DATABASE_URL'),
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME', 'postgres'),
            'USER': os.getenv('DB_USER', 'postgres'),
            'PASSWORD': os.getenv('DB_PASSWORD', '1234'),
            'HOST': os.getenv('DB_HOST', 'localhost'),
            'PORT': os.getenv('DB_PORT', '5432'),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}


AUTH_USER_MODEL = 'accounts.User'

# Password hashing
# ----------------
# Use Argon2 as the primary password hasher (memory-hard, OWASP-recommended)
# and keep PBKDF2 as the fallback so any user that still has a PBKDF2 hash
# in the database can still log in. On the next successful login their
# password will be re-hashed with Argon2 automatically.
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
]

# Argon2 parameters tuned for a 1-CPU / 512 MB instance (Render free tier).
# Defaults are 102400 (100 MiB) memory_cost which is too aggressive for
# constrained hosts; we drop to 64 MiB and 2 iterations for fast logins
# while still being memory-hard.
ARGON2_HASHER = {
    'memory_cost': 65536,   # 64 MiB
    'time_cost': 2,         # 2 iterations
    'parallelism': 1,
}

# JWT Token Configuration
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': False,
}

# Default primary key field type for models that don't specify one explicitly
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ─── Khalti e-Payment (KPG-2) ───────────────────────────────────────
# Docs: https://docs.khalti.com/khalti-epayment/
# Defaults point at Khalti's SANDBOX. There is NO universal public sandbox key:
# each merchant must create a free test account at https://dev.khalti.com/,
# then copy their **Secret Key** from Merchant Dashboard → Settings → Keys and
# set it as KHALTI_SECRET_KEY (in backend/.env). The placeholder below will fail
# authentication ("Invalid token") until you replace it with your own key.
# For production, also switch KHALTI_BASE_URL to https://khalti.com/api/v2.
KHALTI_BASE_URL = os.getenv('KHALTI_BASE_URL', 'https://dev.khalti.com/api/v2')
KHALTI_SECRET_KEY = os.getenv(
    'KHALTI_SECRET_KEY', 'test_secret_key_68791341fdd94846a146f0457ff7b455'
)
# Where Khalti redirects the browser after payment — a frontend route that
# reads ?pidx=…&status=… and calls the verify endpoint.
FRONTEND_URL = os.getenv('FRONTEND_URL', 'http://localhost:5173')
KHALTI_RETURN_URL = os.getenv('KHALTI_RETURN_URL', f'{FRONTEND_URL}/payment/callback')
KHALTI_WEBSITE_URL = os.getenv('KHALTI_WEBSITE_URL', FRONTEND_URL)
# Khalti rejects payments below NPR 10 (1000 paisa).
KHALTI_MIN_AMOUNT_PAISA = int(os.getenv('KHALTI_MIN_AMOUNT_PAISA', '1000'))
KHALTI_TIMEOUT = int(os.getenv('KHALTI_TIMEOUT', '20'))

# Mock/simulation mode. When on, the app simulates Khalti's payment flow with a
# local dummy checkout instead of calling the real gateway — so the end-to-end
# flow is fully testable without a Khalti merchant account. It auto-enables when
# no real secret key is configured (i.e. the shipped placeholder is still in
# place), and turns itself off the moment a real key is set. Force it explicitly
# with KHALTI_MOCK_MODE=True/False.
_KHALTI_PLACEHOLDER_KEY = 'test_secret_key_68791341fdd94846a146f0457ff7b455'
_khalti_mock_env = os.getenv('KHALTI_MOCK_MODE')
if _khalti_mock_env is not None:
    KHALTI_MOCK_MODE = _khalti_mock_env.strip().lower() in ('true', '1', 'yes')
else:
    KHALTI_MOCK_MODE = (
        not KHALTI_SECRET_KEY or KHALTI_SECRET_KEY == _KHALTI_PLACEHOLDER_KEY
    )

# Production security settings
if not DEBUG and not LOCAL_DEVELOPMENT:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
