# Generated by Django 6.0.2 on 2026-03-04 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='max_participants',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum number of participants. Leave blank for unlimited.', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
