# Generated by Django 6.0.2 on 2026-07-22 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_qr_attendance_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Registration fee in NPR. Only charged when payment is required.', max_digits=10),
        ),
        migrations.AddField(
            model_name='event',
            name='payment_required',
            field=models.BooleanField(default=False, help_text='If enabled, students must pay the fee before registering.'),
        ),
    ]
