# Generated by Django 6.0.2 on 2026-07-22 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0004_event_fee_event_payment_required'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pidx', models.CharField(db_index=True, max_length=128, unique=True)),
                ('transaction_id', models.CharField(blank=True, max_length=128, null=True)),
                ('purchase_order_id', models.CharField(max_length=128, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paisa', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('Initiated', 'Initiated'), ('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed'), ('Cancelled', 'Cancelled'), ('Expired', 'Expired'), ('Refunded', 'Refunded')], default='Initiated', max_length=20)),
                ('payment_url', models.URLField(blank=True, default='', max_length=500)),
                ('initiate_response', models.JSONField(blank=True, null=True)),
                ('verification_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Transaction',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'event'], name='payments_pa_user_id_e08383_idx'), models.Index(fields=['status'], name='payments_pa_status_b6726a_idx')],
            },
        ),
    ]
