# Generated by Django 6.0.2 on 2026-03-04 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role_number',
            field=models.CharField(blank=True, help_text='Format: NCE Followed by 3 digits, 3 letters, 3 digits (e.g. NCE123ABC456)', max_length=12, null=True, unique=True),
        ),
    ]
