# Generated by Django 6.0.2 on 2026-03-04 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_role_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='role_number',
            new_name='roll_number',
        ),
    ]
