# Generated by Django 6.0.2 on 2026-03-04 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_role_number_user_roll_number'),
        ('clubs', '0002_department_hod'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Department the user belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='clubs.department'),
        ),
    ]
