# Generated by Django 6.0.2 on 2026-03-04 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_department'),
        ('clubs', '0002_department_hod'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='branch',
            field=models.CharField(blank=True, choices=[('BCT', 'BCT - Computer'), ('BCE', 'BCE - Civil'), ('BEE', 'BEE - Electrical'), ('BEI', 'BEI - Electronics')], help_text='Engineering branch for students', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Department the faculty belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='clubs.department'),
        ),
    ]
