# Generated by Django 6.0.2 on 2026-03-04 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_branch_alter_user_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='roll_number',
            field=models.CharField(blank=True, help_text='Format: NCE0XXBRANCH0XX (e.g. NCE078BCT012)', max_length=12, null=True, unique=True),
        ),
    ]
